import { state, update } from '../../app/store.js';
import { el, openSheet } from '../../shared/dom.js';
import { topbar, collectionManager, centerScrollItem } from '../../shared/components.js';
import { parseFeed } from '../../shared/rss.js';
import { shortDate } from '../../shared/time.js';
import { openImageViewer } from './image-viewer.js';

let selected=Number(localStorage.getItem('pdv2:twitterIndex')||0);let retryTimer=null;let renderGeneration=0;
function stopRetry(){if(retryTimer){clearTimeout(retryTimer);retryTimer=null;}}window.addEventListener('pdv2:before-navigate',stopRetry);
function feedUrl(feed){if(feed.url)return feed.url;return`${state.settings.twitterRssBase}${feed.id}`;}
function proxied(url){if(url.startsWith('/'))return url;const q=new URLSearchParams({url,timeout:'4500'});return`/api/rss?${q}`;}
async function load(feed){const r=await fetch(proxied(feedUrl(feed)),{cache:'no-store'});if(!r.ok)throw new Error(`Twitter RSS取得エラー (${r.status})`);return parseFeed(await r.text(),feed.name);}
function manage(onDone){let sheet;sheet=openSheet(collectionManager({items:state.twitterFeeds,fields:[{key:'name',label:'タブ名',placeholder:'リスト名'},{key:'id',label:'Twitter/X リストID',placeholder:'2087...'},{key:'url',label:'RSS URL（任意）',placeholder:'空ならRSSHubを使用'}],onSave:d=>{update('twitterFeeds',d);sheet.close();selected=0;onDone();}}),{title:'Twitterリスト編集'});}
function isTwitterUrl(url=''){try{const h=new URL(url).hostname.replace(/^www\./,'');return h==='x.com'||h==='twitter.com'||h.endsWith('.twitter.com');}catch{return false;}}
function cleanDescription(html){const doc=new DOMParser().parseFromString(`<div>${html||''}</div>`,'text/html');doc.querySelectorAll('script,style,iframe,video').forEach(n=>n.remove());const images=[...doc.querySelectorAll('img')].map(i=>i.src).filter(src=>/twimg\.com|pbs\.twimg/.test(src)).slice(0,4);const links=[...doc.querySelectorAll('a[href]')].map(a=>a.href).filter(h=>/^https?:/i.test(h)&&!isTwitterUrl(h));doc.querySelectorAll('img').forEach(n=>n.remove());return{text:(doc.body.textContent||'').replace(/\s+/g,' ').trim(),images,links:[...new Set(links)]};}
function isRetweet(item,clean){const text=`${clean?.text||''} ${item?.title||''}`.trim();return/^RT(?:\s|:|@)/i.test(text);}
function appendLinkified(container,text){const re=/(https?:\/\/[^\s<]+)/gi;let last=0;for(const m of text.matchAll(re)){if(m.index>last)container.append(document.createTextNode(text.slice(last,m.index)));let url=m[0].replace(/[),.!?。、「」]+$/,'');const suffix=m[0].slice(url.length);const a=el('a',{class:'tweet-inline-link',href:url,target:'_blank',rel:'noopener noreferrer',text:url});a.addEventListener('click',e=>e.stopPropagation());container.append(a);if(suffix)container.append(document.createTextNode(suffix));last=m.index+m[0].length;}if(last<text.length)container.append(document.createTextNode(text.slice(last)));}
function tweetCard(item){const clean=cleanDescription(item.description);if(isRetweet(item,clean))return null;const card=el('article',{class:'tweet-card'});const text=el('div',{class:'tweet-text'});appendLinkified(text,clean.text||item.title||'');card.append(text);if(clean.images.length){const grid=el('div',{class:`tweet-images count-${Math.min(4,clean.images.length)}`});clean.images.forEach((src,i)=>{const b=el('button',{class:'tweet-image-button',type:'button','aria-label':'画像を拡大'});b.append(el('img',{src,alt:'投稿画像',loading:'lazy',decoding:'async'}));b.onclick=()=>openImageViewer(clean.images,i);grid.append(b);});card.append(grid);}const extra=[...new Set(clean.links)].filter(url=>!clean.text.includes(url));if(extra.length){const links=el('div',{class:'tweet-external-links'});extra.forEach(url=>links.append(el('a',{class:'tweet-external-link',href:url,target:'_blank',rel:'noopener noreferrer',text:url})));card.append(links);}card.append(el('div',{class:'tweet-footer'},[el('span',{class:'media-meta',text:shortDate(item.pubDate)}),el('a',{class:'tweet-open-x',href:item.link,target:'_blank',rel:'noopener noreferrer',text:'Xで開く ↗'})]));return card;}
export async function renderTwitter(root,{navigate,refresh=false}){
  stopRetry();const generation=++renderGeneration;if(selected>=state.twitterFeeds.length)selected=0;const feed=state.twitterFeeds[selected];const screen=el('section',{class:'screen'});screen.append(topbar('SNS',{subtitle:'Twitter / X リスト',actions:[{label:'＋',title:'追加/編集',onClick:()=>manage(()=>renderTwitter(root,{navigate,refresh:true}))},{label:'↻',title:'更新',onClick:()=>renderTwitter(root,{navigate,refresh:true})},{label:'⚙︎',title:'設定',onClick:()=>navigate('settings')}]}));
  if(!feed){screen.append(el('div',{class:'empty',text:'Twitter/Xリストを追加してください'}));root.replaceChildren(screen);return;}
  const chips=el('div',{class:'chips twitter-list-chips'});state.twitterFeeds.forEach((f,i)=>chips.append(el('button',{class:`chip ${i===selected?'active':''}`,type:'button',text:f.name,onclick:()=>{localStorage.setItem(`pdv2:twitterScroll:${selected}`,String(window.scrollY));selected=i;localStorage.setItem('pdv2:twitterIndex',String(i));renderTwitter(root,{navigate});}})));screen.append(chips);const host=el('div',{class:'twitter-feed-host'});screen.append(host);root.replaceChildren(screen);const active=chips.querySelector('.chip.active');if(active)centerScrollItem(chips,active);
  const draw=items=>{if(generation!==renderGeneration)return;const cards=(items||[]).map(tweetCard).filter(Boolean);host.replaceChildren(...(cards.length?cards:[el('div',{class:'empty',text:'表示できる投稿がありません'})]));requestAnimationFrame(()=>window.scrollTo({top:Number(localStorage.getItem(`pdv2:twitterScroll:${selected}`)||0),behavior:'auto'}));};
  try{host.replaceChildren(el('div',{class:'twitter-wake-status'},[el('strong',{text:'SNSを読み込み中…'}),el('span',{text:'RSSHubの起動直後は少し待つ場合があります'})]));const items=await load(feed);if(items.length){draw(items);return;}throw new Error('RSSが空です');}catch(err){if(generation!==renderGeneration)return;host.replaceChildren(el('div',{class:'twitter-wake-status'},[el('strong',{text:'SNSフィードを再確認しています'}),el('span',{text:`${err.message} / 5秒後に1回だけ再試行します`})]));retryTimer=setTimeout(async()=>{if(generation!==renderGeneration)return;try{draw(await load(feed));}catch(e){if(generation===renderGeneration)host.replaceChildren(el('div',{class:'error-box',text:e.message}));}},5000);}
}
