/* Personal Dashboard v2.18.5 */
const nativeFetch2185 = window.fetch.bind(window);
await import('./runtime-v2184.js');
const inheritedFetch2185 = window.fetch.bind(window);

const summaryCache2185 = new Map();
const summaryInflight2185 = new Map();
const typing2185 = new WeakMap();
const GENERIC_RE = /(?:記事の要点をわかりやすく整理|についての記事です|背景や特徴.*(?:整理|確認)|影響や今後.*(?:整理|確認)|記事本文から(?:整理|確認)|主要な内容を確認|元記事(?:本文)?(?:を|で)|詳しくは元記事)/i;

function clean2185(v=''){return String(v||'').replace(/\s+/g,' ').trim()}
function body2185(init){try{return typeof init?.body==='string'?JSON.parse(init.body):{}}catch{return{}}}
function key2185(b={}){return `${clean2185(b.url||b.link)||clean2185(b.title)}::${clean2185(b.mode)||'auto'}::v2185`}
function json2185(v,status=200){return new Response(JSON.stringify(v),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}})}
function href2185(v=''){try{return new URL(v,location.href).href}catch{return String(v||'')}}
function card2185(b={}){const cards=[...document.querySelectorAll('.reader-swipe-card')];const wanted=href2185(b.url||b.link||'');if(wanted){const hit=cards.find(c=>href2185(c.querySelector('.reader-story-open')?.href||'')===wanted);if(hit)return hit}const title=clean2185(b.title);return cards.find(c=>clean2185(c.querySelector('[data-reader-title]')?.textContent||'')===title)||null}

function cancelTyping2185(card){if(!card)return;for(const node of card.querySelectorAll('[data-reader-title],.reader-story-summary-text')){const state=typing2185.get(node);if(state?.raf)cancelAnimationFrame(state.raf);typing2185.delete(node)}}
function type2185(node,target){if(!node)return;const wanted=String(target||'');let state=typing2185.get(node);if(!state){state={target:'',shown:'',raf:0};typing2185.set(node,state)}state.target=wanted;if(!state.target.startsWith(state.shown))state.shown='';if(state.raf)return;const tick=()=>{state.raf=0;if(!node.isConnected)return;const chars=Array.from(state.target),n=Array.from(state.shown).length;if(n>=chars.length)return;state.shown=chars.slice(0,n+(chars.length-n>30?4:2)).join('');node.textContent=state.shown;if(Array.from(state.shown).length<chars.length)state.raf=requestAnimationFrame(tick)};state.raf=requestAnimationFrame(tick)}
function partial2185(text=''){const source=String(text||'').replace(/\r/g,'');const labels=['タイトル','結論/事実','背景/特徴','影響/展望'];const out={};for(let i=0;i<labels.length;i++){const label=labels[i],m=new RegExp(`(?:^|\\n)${label}\\s*[:：]`,'m').exec(source);if(!m)continue;const start=m.index+m[0].length;let end=source.length;for(let j=i+1;j<labels.length;j++){const n=new RegExp(`(?:^|\\n)${labels[j]}\\s*[:：]`,'m').exec(source.slice(start));if(n){end=start+n.index;break}}out[label]=clean2185(source.slice(start,end))}return out}
function paint2185(body,text){const card=card2185(body);if(!card)return;const p=partial2185(text);if(p['タイトル']&&!GENERIC_RE.test(p['タイトル']))type2185(card.querySelector('[data-reader-title]'),p['タイトル']);const rows=[...card.querySelectorAll('.reader-story-summary-row')];['結論/事実','背景/特徴','影響/展望'].forEach((label,i)=>{if(p[label]&&!GENERIC_RE.test(p[label]))type2185(rows[i]?.querySelector('.reader-story-summary-text'),p[label])})}

async function streamedSummary2185(body){
  const response=await nativeFetch2185('/api/summary?stream=1',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/x-ndjson'},cache:'no-store',body:JSON.stringify(body),signal:AbortSignal.timeout(28000)});
  if(!response.ok||!response.body)throw new Error(`summary stream ${response.status}`);
  const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='',acc='',final=null;
  const consume=line=>{if(!line.trim())return;let event;try{event=JSON.parse(line)}catch{return}if(event.type==='delta'&&event.text){acc+=event.text;paint2185(body,acc)}else if(event.type==='done'&&event.summary){final=event.summary}else if(event.type==='error')throw new Error(event.error||'summary stream error')};
  try{while(true){const{value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split(/\r?\n/);buffer=lines.pop()||'';lines.forEach(consume)}buffer+=decoder.decode();if(buffer.trim())consume(buffer)}finally{try{reader.releaseLock()}catch{}}
  cancelTyping2185(card2185(body));
  if(!final)throw new Error('summary stream ended without result');
  return final;
}
async function summary2185(body){const key=key2185(body);if(summaryCache2185.has(key))return summaryCache2185.get(key);if(summaryInflight2185.has(key))return summaryInflight2185.get(key);const task=streamedSummary2185(body).catch(async()=>{cancelTyping2185(card2185(body));const response=await nativeFetch2185('/api/summary?retry=1',{method:'POST',headers:{'Content-Type':'application/json'},cache:'no-store',body:JSON.stringify(body),signal:AbortSignal.timeout(22000)});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error||`summary ${response.status}`);return data}).then(v=>{if(v?.cacheable!==false&&v?.lines?.length===3&&!v.lines.some(r=>GENERIC_RE.test(String(r?.text||''))))summaryCache2185.set(key,v);return v}).finally(()=>{cancelTyping2185(card2185(body));summaryInflight2185.delete(key)});summaryInflight2185.set(key,task);return task}

const WIKI_API2185='https://ja.wikipedia.org/w/api.php';
const WIKI_FALLBACK={classic:[['八甲田雪中行軍遭難事件','極限状況の判断と組織の失敗'],['三毛別羆事件','日本史上最大級の熊害'],['地方病 (日本住血吸虫症)','原因究明から撲滅までの記録'],['ディアトロフ峠事件','不可解な遭難事件'],['フランクリン遠征','北極圏で消えた探検隊'],['メアリー・セレスト','無人で発見された船の謎'],['ツングースカ大爆発','シベリアで起きた巨大爆発'],['ボイニッチ手稿','今も解読されない写本'],['ロアノーク植民地','住民が消えた植民地'],['コティングリー妖精事件','妖精写真をめぐる騒動']],deep:[['ジョーンズタウン','集団心理とカルトの事例'],['ミルグラム実験','権威への服従を扱った心理実験'],['スタンフォード監獄実験','役割と権力をめぐる実験'],['タスキギー梅毒実験','研究倫理の転換点'],['セイラム魔女裁判','恐怖と集団心理の歴史'],['カーゴ・カルト','物質文化と信仰が交差した現象'],['ダンシングマニア','人々が踊り続けた集団現象'],['チューリップ・バブル','投機熱の象徴'],['共有地の悲劇','個人合理性が全体を壊す考え方'],['傍観者効果','集団の中で援助が遅れる心理現象']],trivia:[['エミュー戦争','軍隊が鳥の群れに手を焼いた珍事件'],['風船おじさん','風船で太平洋横断を試みた人物'],['ダーウィン賞','信じがたい失敗談を集めた風刺的な賞'],['イグノーベル賞','笑えて考えさせられる研究'],['空飛ぶスパゲッティ・モンスター教','風刺から生まれた宗教運動'],['ミラクルフルーツ','酸っぱい物を甘く感じさせる果実'],['水中ホッケー','プールの底で行う競技'],['妻問婚','通い婚という婚姻形態'],['トースト・サンドイッチ','パンでパンを挟む料理'],['シュレーディンガーの猫','量子論を説明する思考実験']]};
function jst2185(){const iso=new Date(Date.now()+9*3600000).toISOString();return{date:iso.slice(0,10),month:Number(iso.slice(5,7)),day:Number(iso.slice(8,10))}}
async function wikiGet2185(params,timeout=6500){const url=new URL(WIKI_API2185);Object.entries({format:'json',formatversion:'2',origin:'*',...params}).forEach(([k,v])=>url.searchParams.set(k,String(v)));const response=await nativeFetch2185(url.href,{cache:'no-store',headers:{Accept:'application/json'},signal:AbortSignal.timeout(timeout)});const data=await response.json().catch(()=>({}));if(!response.ok||data?.error)throw new Error(data?.error?.info||`Wikipedia direct ${response.status}`);return data}
function wikiClean2185(v=''){return String(v||'').replace(/\[[0-9０-９]+\]/g,'').replace(/\s+/g,' ').trim()}
async function wikiDailyDirect2185(){
  const{date,month,day}=jst2185();const today=[];
  try{const parsed=await wikiGet2185({action:'parse',page:`${month}月${day}日`,prop:'text',redirects:'1'});const doc=new DOMParser().parseFromString(`<main>${parsed?.parse?.text||''}</main>`,'text/html');const headings=[...doc.querySelectorAll('h2,h3')];const start=headings.find(n=>/^(できごと|出来事)$/.test(wikiClean2185(n.textContent).replace(/\[編集\]$/,'')));if(start){let cursor=(start.closest('.mw-heading')||start).nextElementSibling;while(cursor&&today.length<18){if(/^H[23]$/.test(cursor.tagName)||cursor.matches?.('.mw-heading'))break;for(const li of cursor.querySelectorAll?.('li')||[]){const text=wikiClean2185(li.textContent);const a=[...li.querySelectorAll('a[title]')].find(x=>{const t=wikiClean2185(x.getAttribute('title'));return t&&!t.includes(':')&&!t.includes('#')&&!/^(?:紀元前)?\d{1,4}年$/.test(t)});if(a)today.push([wikiClean2185(a.getAttribute('title')),`${month}月${day}日 — ${text.slice(0,140)}`]);if(today.length>=18)break}cursor=cursor.nextElementSibling}}}catch(error){console.warn('[wiki2185 today]',error?.message||error)}
  const requested=[...today.slice(0,18),...WIKI_FALLBACK.classic,...WIKI_FALLBACK.deep,...WIKI_FALLBACK.trivia];const titles=requested.map(r=>r[0]);const data=await wikiGet2185({action:'query',prop:'extracts|pageimages|info',titles:titles.join('|'),redirects:'1',exintro:'1',explaintext:'1',exchars:'420',piprop:'thumbnail',pithumbsize:'720',inprop:'url'});const map=new Map();for(const n of data?.query?.normalized||[])map.set(n.from,n.to);for(const r of data?.query?.redirects||[])map.set(r.from,r.to);const resolve=t=>{let x=t;for(let i=0;i<5&&map.has(x);i++)x=map.get(x);return x};const pages=new Map((data?.query?.pages||[]).filter(p=>!p.missing).map(p=>[p.title,p]));const items=[];const add=(rows,kind,label)=>{let i=0;for(const[title,reason]of rows){if(i>=10)break;const p=pages.get(resolve(title));if(!p)continue;items.push({id:`${date}:${kind}:${p.pageid||i}`,date,kind,category:label,categoryShort:label,title:p.title,reason,extract:String(p.extract||'').trim(),thumbnail:p.thumbnail?.source||'',url:p.fullurl||`https://ja.wikipedia.org/wiki/${encodeURIComponent(p.title.replace(/ /g,'_'))}`});i++}};add(today,'today','今日の出来事');add(WIKI_FALLBACK.classic,'classic','王道・文学系');add(WIKI_FALLBACK.deep,'deep','考察・読み物系');add(WIKI_FALLBACK.trivia,'trivia','雑学・トリビア系');return{date,dateLabel:`${month}月${day}日`,counts:{today:items.filter(x=>x.kind==='today').length,classic:10,deep:10,trivia:10},items,direct:true}}
async function wikiDaily2185(input,init){const direct=wikiDailyDirect2185();const server=nativeFetch2185(input,{...(init||{}),signal:AbortSignal.timeout(5000)}).then(async r=>{if(!r.ok)throw new Error(`server ${r.status}`);return r});try{return await Promise.any([direct.then(v=>json2185(v)),server])}catch{return inheritedFetch2185(input,init)}}

window.fetch=async function pdv2185Fetch(input,init){let url;try{url=new URL(input instanceof Request?input.url:String(input),location.href)}catch{return inheritedFetch2185(input,init)}if(url.origin===location.origin&&url.pathname==='/api/summary'&&String(init?.method||'GET').toUpperCase()==='POST')return json2185(await summary2185(body2185(init)));if(url.origin===location.origin&&url.pathname==='/api/wikipedia'&&url.searchParams.get('mode')==='daily')return wikiDaily2185(input,init);return inheritedFetch2185(input,init)};
try{if(localStorage.getItem('pdv2:runtime:v2185')!=='1'){localStorage.removeItem('reader-summary-cache-v2180');localStorage.removeItem('pdv2:wikipediaDaily:v213');localStorage.setItem('pdv2:runtime:v2185','1')}}catch{}
